import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import chatsRouter from "./chats";
import messagesRouter from "./messages";
import filesRouter from "./files";
import tasksRouter from "./tasks";
import notificationsRouter from "./notifications";
import aiRouter from "./ai";
import dashboardRouter from "./dashboard";
import adminRouter from "./admin";
import searchRouter from "./search";
import personasRouter from "./personas";
import memoriesRouter from "./memories";
import familyRouter from "./family";
import sharedRouter from "./shared";
import eventsRouter from "./events";
import habitsRouter from "./habits";
import automationsRouter from "./automations";
import insightsRouter from "./insights";
import shoppingRouter from "./shopping";
import budgetRouter from "./budget";
import journalRouter from "./journal";
import goalsRouter from "./goals";
import notesRouter from "./notes";
import voiceRouter from "./voice";

const router: IRouter = Router();

router.use(healthRouter);
router.use(usersRouter);
router.use(chatsRouter);
router.use(messagesRouter);
router.use(filesRouter);
router.use(tasksRouter);
router.use(notificationsRouter);
router.use(aiRouter);
router.use(dashboardRouter);
router.use(adminRouter);
router.use(searchRouter);
router.use(personasRouter);
router.use(memoriesRouter);
router.use(familyRouter);
router.use(sharedRouter);
router.use("/events", eventsRouter);
router.use("/habits", habitsRouter);
router.use("/automations", automationsRouter);
router.use("/insights", insightsRouter);
router.use("/shopping", shoppingRouter);
router.use("/budget", budgetRouter);
router.use("/journal", journalRouter);
router.use("/goals", goalsRouter);
router.use("/notes", notesRouter);
router.use("/voice", voiceRouter);

export default router;
