import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import chatsRouter from "./chats";
import messagesRouter from "./messages";
import filesRouter from "./files";
import tasksRouter from "./tasks";
import notificationsRouter from "./notifications";
import aiRouter from "./ai";
import dashboardRouter from "./dashboard";
import adminRouter from "./admin";
import searchRouter from "./search";
import personasRouter from "./personas";
import memoriesRouter from "./memories";
import familyRouter from "./family";
import sharedRouter from "./shared";
import eventsRouter from "./events";
import habitsRouter from "./habits";
import automationsRouter from "./automations";
import insightsRouter from "./insights";

const router: IRouter = Router();

router.use(healthRouter);
router.use(usersRouter);
router.use(chatsRouter);
router.use(messagesRouter);
router.use(filesRouter);
router.use(tasksRouter);
router.use(notificationsRouter);
router.use(aiRouter);
router.use(dashboardRouter);
router.use(adminRouter);
router.use(searchRouter);
router.use(personasRouter);
router.use(memoriesRouter);
router.use(familyRouter);
router.use(sharedRouter);
router.use("/api/events", eventsRouter);
router.use("/api/habits", habitsRouter);
router.use("/api/automations", automationsRouter);
router.use("/api/insights", insightsRouter);

export default router;
